# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frizbee < Formula
  desc "frizbee is a tool you may throw a tag at and it comes back with a checksum."
  homepage "https://github.com/stacklok/frizbee"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/frizbee/releases/download/v0.0.1/frizbee_0.0.1_darwin_amd64.tar.gz"
      sha256 "787a234e3eaf07ec39bc4b795ca28bdfdd62638c560eecd2b6ab3823d02c426a"

      def install
        bin.install "frizbee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/frizbee/releases/download/v0.0.1/frizbee_0.0.1_darwin_arm64.tar.gz"
      sha256 "a0fcbb534b9fcc18551416ef12d7b118841b83cf071806035d1efa0e4b31fd5b"

      def install
        bin.install "frizbee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/frizbee/releases/download/v0.0.1/frizbee_0.0.1_linux_arm64.tar.gz"
      sha256 "ae696e35c807ce6432242c58f1f942b960db50edee3354e8304c10c92e7f2edc"

      def install
        bin.install "frizbee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/frizbee/releases/download/v0.0.1/frizbee_0.0.1_linux_amd64.tar.gz"
      sha256 "19a4bbb4dbfec1be27fd2e19408719229d1554b0a85858d94780c00524452562"

      def install
        bin.install "frizbee"
      end
    end
  end

  test do
    system "#{bin}/frizbee --help"
  end
end
