# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frizbee < Formula
  desc "frizbee is a tool you may throw a tag at and it comes back with a checksum."
  homepage "https://github.com/stacklok/frizbee"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/stacklok/frizbee/releases/download/v0.1.1/frizbee_0.1.1_darwin_amd64.tar.gz"
      sha256 "b20e33d4b8892d59cf0bfbfcaca59d589f8ae70da9d0157bfedda34341c23baf"

      def install
        bin.install "frizbee"
      end
    end
    on_arm do
      url "https://github.com/stacklok/frizbee/releases/download/v0.1.1/frizbee_0.1.1_darwin_arm64.tar.gz"
      sha256 "674ffc892e2b91ae59cee5e76d3d1898ce61466ab71278586f91b038eacdfdd1"

      def install
        bin.install "frizbee"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/frizbee/releases/download/v0.1.1/frizbee_0.1.1_linux_amd64.tar.gz"
        sha256 "7a95ecab17514401e99ef91048e96dbd81adfb3cdbc7d9e9e42e65ef740c4fb0"

        def install
          bin.install "frizbee"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/frizbee/releases/download/v0.1.1/frizbee_0.1.1_linux_arm64.tar.gz"
        sha256 "35c56dfdae421ff32aaa22a0ad2f022f59c7a64909241f7e67ab0f10adb884e5"

        def install
          bin.install "frizbee"
        end
      end
    end
  end

  test do
    system "#{bin}/frizbee --help"
  end
end
