# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mecatl < Formula
  desc "Agent harness for cloud-native workloads, with server and terminal UI"
  homepage "https://github.com/stacklok/mecatl"
  version "0.0.40"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.40/mecatl_0.0.40_darwin_amd64.tar.gz"
      sha256 "f73638c20ea7f499d169ba930de2a6070623bbc4c115c1846eb0a6695d068795"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.40/mecatl_0.0.40_darwin_arm64.tar.gz"
      sha256 "7a296c924b2f6bfa4c322be9d83ad164406a9f3e6f666c1011e691e704ee2b26"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.40/mecatl_0.0.40_linux_amd64.tar.gz"
      sha256 "0e5c641adf5c5d954a27572f0ef27b5314842c76e249f8cb4025eac7a56841e7"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.40/mecatl_0.0.40_linux_arm64.tar.gz"
      sha256 "22e653df7063ce908202a80eeee0f8fff2ce3c3fd5bd56f4868984c375eeb997"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  test do
    assert_match "mecated v0.0.40", shell_output("#{bin}/mecated --version")
    assert_match "mecatui v0.0.40", shell_output("#{bin}/mecatui --version")
  end
end
