# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mecatl < Formula
  desc "Agent harness for cloud-native workloads, with server and terminal UI"
  homepage "https://github.com/stacklok/mecatl"
  version "0.0.47"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.47/mecatl_0.0.47_darwin_amd64.tar.gz"
      sha256 "5ef3429f72dcf773705cb324f7f4b230de0e3eb78689ef9dfb14c5a1d8a5b5cd"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.47/mecatl_0.0.47_darwin_arm64.tar.gz"
      sha256 "910c05e8dc4fb4e2a6651d3f5825fab7deb40b1f130a5b29d9ee4473c1ec1ff5"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.47/mecatl_0.0.47_linux_amd64.tar.gz"
      sha256 "98df83a9a1084fec8e6c8dc1f11e1abc9b93d883293f2189df7b10c61f26ff46"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.47/mecatl_0.0.47_linux_arm64.tar.gz"
      sha256 "444c3e88d3334513180042d945ee350d71d805ae89dd7f5f35e7155f0d22e5f5"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  test do
    assert_match "mecated v0.0.47", shell_output("#{bin}/mecated --version")
    assert_match "mecatui v0.0.47", shell_output("#{bin}/mecatui --version")
  end
end
