# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mecatl < Formula
  desc "Agent harness for cloud-native workloads, with server and terminal UI"
  homepage "https://github.com/stacklok/mecatl"
  version "0.0.32"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.32/mecatl_0.0.32_darwin_amd64.tar.gz"
      sha256 "887d1c83777698079008715fafe394c53a5f5bc650f5b5aef733f4ad4523d374"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.32/mecatl_0.0.32_darwin_arm64.tar.gz"
      sha256 "0259dbd2f4a4dc50e3f91b8bd9bd4ec295dbc97dc52c8e870b41a5c71fe00294"

      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.32/mecatl_0.0.32_linux_amd64.tar.gz"
      sha256 "f9fb8aadf10d09c32db230ecd6a6944930616c34cf7888c3e4ab201cfb9cac70"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mecatl/releases/download/v0.0.32/mecatl_0.0.32_linux_arm64.tar.gz"
      sha256 "9a95b35e1af778b2e0ea6a2b94ab158c08455f537f6983569de58c74b396a479"
      define_method(:install) do
        bin.install "mecated"
        bin.install "mecatui"
      end
    end
  end

  test do
    assert_match "mecated v0.0.32", shell_output("#{bin}/mecated --version")
    assert_match "mecatui v0.0.32", shell_output("#{bin}/mecatui --version")
  end
end
