# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Medic < Formula
  desc "Medic is the client CLI for interacting with Mediator by Stacklok."
  homepage "https://github.com/stacklok/mediator"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/mediator/releases/download/v0.0.9/medic_0.0.9_darwin_arm64.tar.gz"
      sha256 "e20cd34865b20eae60d0f427a1fbb48de14908bd188e27193dfac1e4f2528a43"

      def install
        bin.install "medic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/mediator/releases/download/v0.0.9/medic_0.0.9_darwin_amd64.tar.gz"
      sha256 "0c4fad44e59a98e43b54d7b6b9d3f44058f2a6206bb6f3a3d4d538da3e784e71"

      def install
        bin.install "medic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/mediator/releases/download/v0.0.9/medic_0.0.9_linux_arm64.tar.gz"
      sha256 "8bb7ae1e4bd0eff279280df43d6e0e6c84c127cb4fe670136fcf6552115ab6ee"

      def install
        bin.install "medic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/mediator/releases/download/v0.0.9/medic_0.0.9_linux_amd64.tar.gz"
      sha256 "c7020bf46428505afb47af6fcf028af97a785a07e4a5d7a4446bc8bf6a09a6b8"

      def install
        bin.install "medic"
      end
    end
  end

  test do
    system "#{bin}/medic --help"
  end
end
