# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minder < Formula
  desc "minder is the client CLI for interacting with Minder by Stacklok."
  homepage "https://github.com/stacklok/minder"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/minder/releases/download/v0.0.17/minder_0.0.17_darwin_arm64.tar.gz"
      sha256 "6679021abb4ec38142a91913add1042b067896957ec7d37af7eb65201c4df3b4"

      def install
        bin.install "minder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/minder/releases/download/v0.0.17/minder_0.0.17_darwin_amd64.tar.gz"
      sha256 "039b99c20c7920dc540cb25129702775d488f372804f32d43daa7f721b3a6897"

      def install
        bin.install "minder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/minder/releases/download/v0.0.17/minder_0.0.17_linux_arm64.tar.gz"
      sha256 "5f01bcf502490f6bd3476ddbc1b1e3220ec1172f983a954ca66e0d22a26ec975"

      def install
        bin.install "minder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/minder/releases/download/v0.0.17/minder_0.0.17_linux_amd64.tar.gz"
      sha256 "9ad9deff593d34b22c3c036554ef191f0ec7b87e376c24151f5e2a3235b31960"

      def install
        bin.install "minder"
      end
    end
  end

  test do
    system "#{bin}/minder --help"
  end
end
