# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minder < Formula
  desc "minder is the client CLI for interacting with Minder by Stacklok."
  homepage "https://github.com/stacklok/minder"
  version "0.0.50"

  on_macos do
    on_intel do
      url "https://github.com/stacklok/minder/releases/download/v0.0.50/minder_0.0.50_darwin_amd64.tar.gz"
      sha256 "82c9e740044f4bb5fff6d52188361f7d34f6b225ba686582ab012e05e9acb1e6"

      def install
        bin.install "minder"
      end
    end
    on_arm do
      url "https://github.com/stacklok/minder/releases/download/v0.0.50/minder_0.0.50_darwin_arm64.tar.gz"
      sha256 "637979ff637e6061732e84d318af1d0f14efabf650df1d2e792ee227f9a9dd14"

      def install
        bin.install "minder"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/minder/releases/download/v0.0.50/minder_0.0.50_linux_amd64.tar.gz"
        sha256 "bf54c8a6597aeda52a4d87db8121f253ec9e3110b890a5a9849eceb16ac28d09"

        def install
          bin.install "minder"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/minder/releases/download/v0.0.50/minder_0.0.50_linux_arm64.tar.gz"
        sha256 "7edc2f18c9815463f02e5ea3cee78a569f293e716aa610be809b29bbeb3b5ce9"

        def install
          bin.install "minder"
        end
      end
    end
  end

  test do
    system "#{bin}/minder --help"
  end
end
