# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modelith < Formula
  desc "Tooling for authoring, validating, and rendering domain models"
  homepage "https://github.com/stacklok/modelith"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/modelith/releases/download/v0.1.0/modelith_0.1.0_darwin_amd64.tar.gz"
      sha256 "ef8fb8858f76ba94db13490019dcf5cc9bdcc87fca616766037d7b8b306021ca"

      define_method(:install) do
        bin.install "modelith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/modelith/releases/download/v0.1.0/modelith_0.1.0_darwin_arm64.tar.gz"
      sha256 "7d4103b0ef4313f9015bc6e969b827ed70e6727af11efedfa947252a9900212a"

      define_method(:install) do
        bin.install "modelith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/modelith/releases/download/v0.1.0/modelith_0.1.0_linux_amd64.tar.gz"
      sha256 "e750efa24d0ea062ecb1ce4f05a246c600b0977f4787da4ee36f380f98db8c9f"
      define_method(:install) do
        bin.install "modelith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/modelith/releases/download/v0.1.0/modelith_0.1.0_linux_arm64.tar.gz"
      sha256 "11d2eae216a47c677bbb822563b61b1dfa9de90a909ef2002f166e68cacb7a34"
      define_method(:install) do
        bin.install "modelith"
      end
    end
  end

  test do
    system "#{bin}/modelith --version"
  end
end
