# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modelith < Formula
  desc "Tooling for authoring, validating, and rendering domain models"
  homepage "https://github.com/stacklok/modelith"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/modelith/releases/download/v0.5.0/modelith_0.5.0_darwin_amd64.tar.gz"
      sha256 "c6ff089ca567ff98481d4f01c8f01e8f278e60f33a769e28518ba5031b4797ec"

      define_method(:install) do
        bin.install "modelith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/modelith/releases/download/v0.5.0/modelith_0.5.0_darwin_arm64.tar.gz"
      sha256 "7f0644f5ec2f98c37f4a3fced4b1ee149298053f75be28993b042dd969e87bc6"

      define_method(:install) do
        bin.install "modelith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/modelith/releases/download/v0.5.0/modelith_0.5.0_linux_amd64.tar.gz"
      sha256 "df779ee7092d588c1103649c3f274b65da6da212a06a69b823a917e2efce37af"
      define_method(:install) do
        bin.install "modelith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacklok/modelith/releases/download/v0.5.0/modelith_0.5.0_linux_arm64.tar.gz"
      sha256 "3e116ed400f068efcaf0abf73a881b867e9fba0b065618c313659ca7ea77349d"
      define_method(:install) do
        bin.install "modelith"
      end
    end
  end

  test do
    system "#{bin}/modelith --version"
  end
end
