# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibetool < Formula
  desc "vibetool is a lightweight, secure, and fast manager for MCP (Model Context Protocol) servers"
  homepage "https://github.com/stacklok/vibetool"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/vibetool/releases/download/v0.0.1/vibetool_0.0.1_darwin_amd64.tar.gz"
      sha256 "21a66feae3fb797d0f4290f5eafb0380b39e0c9d2138bb57c76dea445a54f9d2"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/vibetool/releases/download/v0.0.1/vibetool_0.0.1_darwin_arm64.tar.gz"
      sha256 "8d4ab33d84d87072f06a23a019fda35fd5b85d1e4f482010721713a1cb2a0221"

      def install
        bin.install "vt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/vibetool/releases/download/v0.0.1/vibetool_0.0.1_linux_amd64.tar.gz"
        sha256 "f16bb735bdfd0d528f7e3a503ea6afc6d6c5122656a0932f4ccf24fa1526dac6"

        def install
          bin.install "vt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/vibetool/releases/download/v0.0.1/vibetool_0.0.1_linux_arm64.tar.gz"
        sha256 "429480d46b3d7c27cdcc40758e1b160b7a5ce1ce896326a48ec168197c7c1fcd"

        def install
          bin.install "vt"
        end
      end
    end
  end

  test do
    system "#{bin}/vt --help"
  end
end
