# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vt < Formula
  desc "vibetool is a lightweight, secure, and fast manager for MCP (Model Context Protocol) servers"
  homepage "https://github.com/stacklok/vibetool"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacklok/vibetool/releases/download/v0.0.2/vibetool_0.0.2_darwin_amd64.tar.gz"
      sha256 "761c1718134f756408df96d829478f2e3863e944c8d0fb86b9e3bdc5fde1f015"

      def install
        bin.install "vt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacklok/vibetool/releases/download/v0.0.2/vibetool_0.0.2_darwin_arm64.tar.gz"
      sha256 "a262ec5de98a7195259f0c48973be2d7d369e074cbfb7845331de7b4851b682f"

      def install
        bin.install "vt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/vibetool/releases/download/v0.0.2/vibetool_0.0.2_linux_amd64.tar.gz"
        sha256 "fe453b67914f759a33dc2c5e53e96ef2720dbde8336ebcb9a813ea37fad3319a"

        def install
          bin.install "vt"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacklok/vibetool/releases/download/v0.0.2/vibetool_0.0.2_linux_arm64.tar.gz"
        sha256 "6f3f156135db0fb8bff0d85a78f8f904d024a8c72804c9e601564bcf05c4e660"

        def install
          bin.install "vt"
        end
      end
    end
  end

  test do
    system "#{bin}/vt --help"
  end
end
